spin_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
name = "raw-wit-test"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "raw-wit-test"
source = "target/wasm32-wasi/release/raw_wit_test.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
